version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: signal-chat-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-signal_chat}
    command: mongod --noauth
    volumes:
      - mongodb_data:/data/db
    networks:
      - signal-chat-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo-express:
    image: mongo-express:1.0.2
    container_name: signal-chat-mongo-express
    restart: unless-stopped
    ports:
      - "3000:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - signal-chat-network

volumes:
  mongodb_data:
    driver: local

networks:
  signal-chat-network:
    driver: bridge